"""add tap stability to attempts

Revision ID: 58d76a746a10
Revises: d7bd4e438958
Create Date: 2026-06-14 10:44:04.747631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d76a746a10'
down_revision = 'd7bd4e438958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tap_stability', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_column('tap_stability')

    # ### end Alembic commands ###
