"""Consolidate databases and add academy columns

Revision ID: 975ea01af41c
Revises: dd1fb396ec7b
Create Date: 2026-06-14 14:48:15.587252

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "975ea01af41c"
down_revision = "dd1fb396ec7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("min_bpm", sa.Integer(), nullable=False),
        sa.Column("max_bpm", sa.Integer(), nullable=False),
        sa.Column("genre", sa.String(length=50), nullable=False),
        sa.Column("difficulty", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crates")),
        sa.UniqueConstraint("name", name=op.f("uq_crates_name")),
    )
    op.create_table(
        "anchor_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("anchor_bpm", sa.Integer(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("next_review_at", sa.DateTime(), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("metrical_match_streak", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_anchor_schedules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anchor_schedules")),
        sa.UniqueConstraint("user_id", "anchor_bpm", name=op.f("uq_anchor_schedules_user_id")),
    )
    with op.batch_alter_table("anchor_schedules", schema=None) as batch_op:
        batch_op.create_index("idx_schedules_due", ["user_id", "next_review_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_anchor_schedules_user_id"), ["user_id"], unique=False)

    op.create_table(
        "challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crate_id", sa.Integer(), nullable=False),
        sa.Column("true_bpm", sa.Float(), nullable=False),
        sa.Column("genre", sa.String(length=50), nullable=False),
        sa.Column("beat_recipe_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crate_id"],
            ["crates.id"],
            name=op.f("fk_challenges_crate_id_crates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenges")),
    )
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_challenges_crate_id"), ["crate_id"], unique=False)

    op.create_table(
        "reference_tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crate_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("artist", sa.String(length=150), nullable=False),
        sa.Column("bpm", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crate_id"],
            ["crates.id"],
            name=op.f("fk_reference_tracks_crate_id_crates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_tracks")),
    )
    with op.batch_alter_table("reference_tracks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reference_tracks_crate_id"), ["crate_id"], unique=False
        )

    op.create_table(
        "attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=True),
        sa.Column("guessed_bpm", sa.Float(), nullable=False),
        sa.Column("true_bpm", sa.Float(), nullable=False),
        sa.Column("bpm_error", sa.Float(), nullable=False),
        sa.Column("percent_error", sa.Float(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("rating", sa.String(length=50), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("client_uuid", sa.String(length=100), nullable=True),
        sa.Column("crate_name", sa.String(length=100), nullable=True),
        sa.Column("metrical_multiplier", sa.Float(), nullable=False),
        sa.Column("tap_stability", sa.Float(), nullable=True),
        sa.Column("is_anchor", sa.Boolean(), nullable=False),
        sa.Column("anchor_bpm", sa.Integer(), nullable=True),
        sa.Column("anchor_level", sa.Integer(), nullable=True),
        sa.Column("module", sa.String(length=50), server_default="count_me_in", nullable=False),
        sa.Column("skill_tag", sa.String(length=50), nullable=True),
        sa.Column("input_method", sa.String(length=20), nullable=True),
        sa.Column("phase_error_ms", sa.Float(), nullable=True),
        sa.Column("hand", sa.String(length=10), nullable=True),
        sa.Column("phrase_length", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenges.id"],
            name=op.f("fk_attempts_challenge_id_challenges"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_attempts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
        sa.UniqueConstraint("client_uuid", name=op.f("uq_attempts_client_uuid")),
    )
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.create_index(
            "idx_attempts_ari", ["user_id", "is_anchor", "anchor_bpm", "created_at"], unique=False
        )
        batch_op.create_index("idx_attempts_client_uuid", ["client_uuid"], unique=False)
        batch_op.create_index(
            "idx_attempts_skill_profile",
            ["user_id", "module", "skill_tag", "percent_error"],
            unique=False,
        )
        batch_op.create_index("idx_attempts_user_created", ["user_id", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_attempts_challenge_id"), ["challenge_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_attempts_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attempts_user_id"))
        batch_op.drop_index(batch_op.f("ix_attempts_challenge_id"))
        batch_op.drop_index("idx_attempts_user_created")
        batch_op.drop_index("idx_attempts_skill_profile")
        batch_op.drop_index("idx_attempts_client_uuid")
        batch_op.drop_index("idx_attempts_ari")

    op.drop_table("attempts")
    with op.batch_alter_table("reference_tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reference_tracks_crate_id"))

    op.drop_table("reference_tracks")
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_challenges_crate_id"))

    op.drop_table("challenges")
    with op.batch_alter_table("anchor_schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_anchor_schedules_user_id"))
        batch_op.drop_index("idx_schedules_due")

    op.drop_table("anchor_schedules")
    op.drop_table("crates")
    # ### end Alembic commands ###
