"""add dj roomba models and key fields to track_tempo_annotation

Revision ID: ae04d16815c6
Revises: 975ea01af41c
Create Date: 2026-06-14 20:42:01.168326

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ae04d16815c6"
down_revision = "975ea01af41c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist_imports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_playlist_id", sa.String(length=50), nullable=False),
        sa.Column("playlist_name", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_playlist_imports_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist_imports")),
        sa.UniqueConstraint("user_id", "source_playlist_id", name="uq_user_playlist_import"),
    )
    with op.batch_alter_table("playlist_imports", schema=None) as batch_op:
        batch_op.create_index("idx_pi_user_imported", ["user_id", "imported_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_playlist_imports_user_id"), ["user_id"], unique=False)

    op.create_table(
        "track_feature_annotations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("camelot_key", sa.String(length=4), nullable=True),
        sa.Column("energy_tag", sa.String(length=20), nullable=True),
        sa.Column("energy_score", sa.Float(), nullable=True),
        sa.Column("phrase_hint", sa.Integer(), nullable=True),
        sa.Column("timbre_vector", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track_identities.id"],
            name=op.f("fk_track_feature_annotations_track_id_track_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track_feature_annotations")),
        sa.UniqueConstraint("track_id", "source", name="uq_tfa_track_source"),
    )
    with op.batch_alter_table("track_feature_annotations", schema=None) as batch_op:
        batch_op.create_index("idx_tfa_track_id", ["track_id"], unique=False)

    op.create_table(
        "playlist_tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist_imports.id"],
            name=op.f("fk_playlist_tracks_playlist_id_playlist_imports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track_identities.id"],
            name=op.f("fk_playlist_tracks_track_id_track_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist_tracks")),
        sa.UniqueConstraint("playlist_id", "position", name="uq_playlist_position"),
        sa.UniqueConstraint("playlist_id", "track_id", name="uq_playlist_track"),
    )
    with op.batch_alter_table("playlist_tracks", schema=None) as batch_op:
        batch_op.create_index("idx_pt_playlist_position", ["playlist_id", "position"], unique=False)
        batch_op.create_index("idx_pt_track_id", ["track_id"], unique=False)

    op.create_table(
        "transition_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("from_track_id", sa.Integer(), nullable=False),
        sa.Column("to_track_id", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("tempo_score", sa.Float(), nullable=False),
        sa.Column("harmonic_score", sa.Float(), nullable=False),
        sa.Column("energy_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("stale_reason", sa.String(length=100), nullable=True),
        sa.Column("risk_flags_json", sa.JSON(), nullable=True),
        sa.Column("explanation_json", sa.JSON(), nullable=True),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_track_id"],
            ["track_identities.id"],
            name=op.f("fk_transition_candidates_from_track_id_track_identities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist_imports.id"],
            name=op.f("fk_transition_candidates_playlist_id_playlist_imports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_track_id"],
            ["track_identities.id"],
            name=op.f("fk_transition_candidates_to_track_id_track_identities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transition_candidates")),
        sa.UniqueConstraint(
            "playlist_id", "from_track_id", "to_track_id", name="uq_transition_pair"
        ),
    )
    with op.batch_alter_table("transition_candidates", schema=None) as batch_op:
        batch_op.create_index("idx_tc_from_track", ["playlist_id", "from_track_id"], unique=False)
        batch_op.create_index("idx_tc_playlist_score", ["playlist_id", "total_score"], unique=False)

    with op.batch_alter_table("track_tempo_annotations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("musical_key", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("key_mode", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("camelot_key", sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column("key_confidence", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track_tempo_annotations", schema=None) as batch_op:
        batch_op.drop_column("key_confidence")
        batch_op.drop_column("camelot_key")
        batch_op.drop_column("key_mode")
        batch_op.drop_column("musical_key")

    with op.batch_alter_table("transition_candidates", schema=None) as batch_op:
        batch_op.drop_index("idx_tc_playlist_score")
        batch_op.drop_index("idx_tc_from_track")

    op.drop_table("transition_candidates")
    with op.batch_alter_table("playlist_tracks", schema=None) as batch_op:
        batch_op.drop_index("idx_pt_track_id")
        batch_op.drop_index("idx_pt_playlist_position")

    op.drop_table("playlist_tracks")
    with op.batch_alter_table("track_feature_annotations", schema=None) as batch_op:
        batch_op.drop_index("idx_tfa_track_id")

    op.drop_table("track_feature_annotations")
    with op.batch_alter_table("playlist_imports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playlist_imports_user_id"))
        batch_op.drop_index("idx_pi_user_imported")

    op.drop_table("playlist_imports")
    # ### end Alembic commands ###
