"""init schema with index and cascades

Revision ID: d918b9fa6494
Revises: 
Create Date: 2026-06-14 09:18:57.067421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd918b9fa6494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('min_bpm', sa.Integer(), nullable=False),
    sa.Column('max_bpm', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crates')),
    sa.UniqueConstraint('name', name=op.f('uq_crates_name'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('tags_string', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('max_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crate_id', sa.Integer(), nullable=False),
    sa.Column('true_bpm', sa.Float(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('beat_recipe_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crate_id'], ['crates.id'], name=op.f('fk_challenges_crate_id_crates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenges_crate_id'), ['crate_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('guessed_bpm', sa.Float(), nullable=False),
    sa.Column('true_bpm', sa.Float(), nullable=False),
    sa.Column('bpm_error', sa.Float(), nullable=False),
    sa.Column('percent_error', sa.Float(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=50), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=100), nullable=True),
    sa.Column('crate_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_attempts_challenge_id_challenges'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts')),
    sa.UniqueConstraint('client_uuid', name=op.f('uq_attempts_client_uuid'))
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index('idx_attempts_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_challenge_id'), ['challenge_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_challenge_id'))
        batch_op.drop_index('idx_attempts_user_created')

    op.drop_table('attempts')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenges_crate_id'))

    op.drop_table('challenges')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('crates')
    # ### end Alembic commands ###
