"""add database binds and anchor columns

Revision ID: dd1fb396ec7b
Revises: 58d76a746a10
Create Date: 2026-06-14 10:59:57.085891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1fb396ec7b'
down_revision = '58d76a746a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenges_crate_id'))

    op.drop_table('challenges')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_attempts_user_created'))
        batch_op.drop_index(batch_op.f('ix_attempts_challenge_id'))

    op.drop_table('attempts')
    op.drop_table('crates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('min_bpm', sa.INTEGER(), nullable=False),
    sa.Column('max_bpm', sa.INTEGER(), nullable=False),
    sa.Column('genre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crates')),
    sa.UniqueConstraint('name', name=op.f('uq_crates_name'))
    )
    op.create_table('attempts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), nullable=True),
    sa.Column('guessed_bpm', sa.FLOAT(), nullable=False),
    sa.Column('true_bpm', sa.FLOAT(), nullable=False),
    sa.Column('bpm_error', sa.FLOAT(), nullable=False),
    sa.Column('percent_error', sa.FLOAT(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.VARCHAR(length=50), nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('client_uuid', sa.VARCHAR(length=100), nullable=True),
    sa.Column('crate_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('metrical_multiplier', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('tap_stability', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_attempts_challenge_id_challenges'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts')),
    sa.UniqueConstraint('client_uuid', name=op.f('uq_attempts_client_uuid'))
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_challenge_id'), ['challenge_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_attempts_user_created'), ['user_id', 'created_at'], unique=False)

    op.create_table('challenges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('crate_id', sa.INTEGER(), nullable=False),
    sa.Column('true_bpm', sa.FLOAT(), nullable=False),
    sa.Column('genre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('beat_recipe_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['crate_id'], ['crates.id'], name=op.f('fk_challenges_crate_id_crates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenges_crate_id'), ['crate_id'], unique=False)

    # ### end Alembic commands ###
